version: 2.1
executors:
  node:
    parameters:
      image:
        type: string
        default: "10"
    docker:
      - image: circleci/node:<< parameters.image >>

aliases:
  restore_cache: &restore_cache
    restore_cache:
      name: Restore node_modules cache
      keys:
        - yarn-cache-{{ checksum "yarn.lock" }}

  install_node_modules: &install_node_modules
    run:
      name: Install node modules
      command: yarn --frozen-lockfile

  persist_cache: &persist_cache
    save_cache:
      name: Save node modules cache
      key: yarn-cache-{{ checksum "yarn.lock" }}
      paths:
        - ~/.cache

commands:
  run-script:
    parameters:
      script:
        type: string
    steps:
      - checkout
      - <<: *restore_cache
      - <<: *install_node_modules
      - <<: *persist_cache
      - run: "yarn << parameters.script >>"

jobs:
  lint:
    executor: node
    steps:
      - run-script:
          script: lint
  test:
    executor: node
    steps:
      - run-script:
          script: test

  publish:
    executor: node
    steps:
      - checkout

workflows:
  version: 2
  build-test:
    jobs:
      - lint
      - test
      - publish:
          requires:
            - lint
            - test
