version: 2.1
executors:
  node:
    parameters:
      image:
        type: string
        default: "10"
    docker:
      - image: circleci/node:<< parameters.image >>

aliases:
  restore_cache: &restore_cache
    restore_cache:
      name: Restore node_modules cache
      keys:
        - yarn-cache-{{ checksum "yarn.lock" }}

  install_node_modules: &install_node_modules
    run:
      name: Install node modules
      command: yarn --frozen-lockfile

  persist_cache: &persist_cache
    save_cache:
      name: Persist yarn cache directory between builds
      key: yarn-cache-{{ checksum "yarn.lock" }}
      paths:
        - ~/.cache

commands:
  run-script:
    parameters:
      script:
        type: string
    steps:
      - checkout
      - <<: *restore_cache
      - <<: *install_node_modules
      - <<: *persist_cache
      - run: "yarn run << parameters.script >>"

jobs:
  # TODO: add bootstrap job which clones gatsbyjs/gatsby

  lint:
    executor: node
    steps:
      - run-script:
          script: lint

  test:
    executor: node
    steps:
      - run-script:
          script: test

  build:
    executor: node
    steps:
      - run-script:
          script: build

  publish:
    executor: node
    steps:
      - checkout
      - <<: *restore_cache
      - <<: *install_node_modules
      - <<: *persist_cache
      - add_ssh_keys:
          fingerprints:
            - 02:dd:9e:d2:26:04:d2:5c:d5:8e:db:a7:96:9a:25:a5
      - run: git config --global user.name "GatsbyJS Bot"
      - run: git config --global user.email "admin@gatsbyjs.com"
      - run: yarn run publish
      - run: node scripts/sync-repos.js

workflows:
  version: 2
  build-test:
    jobs:
      - lint
      - test
      - build
      - publish:
          requires:
            - lint
            - test
            - build
          filters:
            branches:
              only: master
